### PR TITLE
Add the agenda 

### PR DESCRIPTION
**Pull request by InnaAtanasova**
In this PR:
- I added the Agenda for review
- Moved the sponsors to a separate page
- Added a new section under the agenda with the sponsors logos that are links to their websites

For the Agenda:
- the timezone switch that you will see on the images you won't see on the website if you are in Germany as it doesn't make sense to hate it
- the links under the speakers you also won't see on the website coz currently there are no presentation links. I made them just to have the CSS and HTML ready. Once I know the API I will show them
- there are many speakers with missing images and info. There are speakers with info "I will add some later" :) 
- let me know how you feel about the icons I used :) I can easily change them if you find better
- the above is valid for the whole design :) Jumaine can take a look and suggest improvement. There's no Figma for the design, I improvised and did the design as I was coding, so he can just call me to discuss his ideas
- if I forgot something (probably did), let me know

The (DON'T MERGE YET): you can download my fork and run locally the `index.html` file and see how everything looks like. If you are ok with the design, the missing speakers logos, info, etc. you can merge it. Functionality wise it's all there. 

Enjoy the weekend :)

Here are some pics:

Screenshot 2024-04-12 at 6 13 42 PM
Screenshot 2024-04-12 at 4 56 08 PM
Screenshot 2024-04-12 at 6 33 29 PM
Screenshot 2024-04-12 at 6 12 21 PM
Screenshot 2024-04-12 at 4 56 50 PM
Screenshot 2024-04-12 at 4 57 06 PM
Screenshot 2024-04-12 at 6 18 47 PM
Screenshot 2024-04-12 at 6 34 27 PM
Screenshot 2024-04-12 at 6 34 59 PM
Screenshot 2024-04-12 at 6 35 19 PM

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
Updates 15.04.2024
- removed the Join waiting list button and Tito section
- replaced the Join waiting list button with agenda and sponsors buttons
- the room filtering options now show W1 | W2 together
- added Back button to the sponsors page and reduced the white space
- removed the sponsorship packages table
Screenshot 2024-04-15 at 11 52 15 AM
Screenshot 2024-04-15 at 11 52 04 AM
Screenshot 2024-04-15 at 11 51 50 AM

**Comment by InnaAtanasova** [comment]
I haven't pushed this variation. Let me know what you think about it :)

Screenshot 2024-04-15 at 12 20 51 PM

**Comment by InnaAtanasova** [comment]
Or maybe this :) 

Screenshot 2024-04-15 at 4 49 00 PM

**Comment by vobu** [comment]
> I haven't pushed this variation. Let me know what you think about it :)
> 
> Screenshot 2024-04-15 at 1 34 52 PM

ohhhhhh, i really like this one - could you put it on the PR please?
The rest looks nice to me - thanks again for putting in the work! Looking forward to publishing this soon :)

**Pull request merged**
